[package]
name = "pchmd_server"
version = "0.1.0"
authors = ["Melvin Wang <melvin.mc.wang@gmail.com>"]
edition = "2021"

[dependencies]
capnp = "0.14.6"
libc = "0.2.126"

[build-dependencies]
bindgen = "0.59.2"
capnpc = "0.14.7"
