[package]
name = "pchmd_server"
version = "0.1.0"
authors = ["Melvin Wang <melvin.mc.wang@gmail.com>"]
edition = "2021"

[dependencies]
capnp = "0.14.6"
lm-sensors = "0.1.4"

[build-dependencies]
capnpc = "0.14.7"
